# version: '3.1'

services:
    source_db:
        image: postgres:15.6 # using older verison to be compatible with the python service
        restart: always
        ports:
            - 5433:5432
        environment:
            NETWORK_ACCESS: internal
            POSTGRES_DB: source_db
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./volumes/postgres/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
            # - ./volumes/postgres/data_source:/var/lib/postgresql/data_source
        networks:
            - local-freecodecamp-dev

    destination_db:
        image: postgres:15.6 # using older verison to be compatible with the python service
        restart: always
        ports:
            - 5434:5432
        environment:
            NETWORK_ACCESS: internal
            POSTGRES_DB: destination_db
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        # No volumes for destination db. We do not want to persist data here
        # volumes:
        #     - ./volumes/postgres/data_destination:/var/lib/postgresql/data_destination
        networks:
            - local-freecodecamp-dev

    etl_script:
        build:
            context: .
            dockerfile: Dockerfile
        # command: ['python', 'etl_script.py']
        depends_on:
            - source_db
            - destination_db
        networks:
            - local-freecodecamp-dev

    dbt:
        image: ghcr.io/dbt-labs/dbt-postgres:latest
        depends_on:
            etl_script:
                condition: service_completed_successfully
        command: ['run', '--profiles-dir', '/root', '--project-dir', '/dbt']
        environment:
            DBT_PROFILE: default
            DBT_TARGET: dev
        volumes:
            - ./custom_postgres:/dbt
            - ~/.dbt:/root
        networks:
            - local-freecodecamp-dev

    # PGADMIN4 NO LONGER WORKS. USE DBEAVER https://dbeaver.io/download/

    # reverseproxy:
    #     image: jwilder/nginx-proxy:latest
    #     depends_on:
    #         - pgadmin
    #         - postgres_db
    #     ports:
    #         - 8080:80
    #         - 4434:443
    #     volumes:
    #         - /var/run/docker.sock:/tmp/docker.sock:ro
    #         - ./volumes/reverseproxy/certs:/etc/nginx/certs:ro
    #         - ./volumes/reverseproxy/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
    #         - ./volumes/reverseproxy/logs:/var/log/nginx:rw
    #         - ./volumes/reverseproxy/vhost:/ect/nginx/vhost.d:rw
    #         - ./volumes/reverseproxy/html:/usr/share/nginx/html:rw
    #     networks:
    #         - local-freecodecamp-dev

networks:
    local-freecodecamp-dev:
