from dotenv import load_dotenv
import os

load_dotenv()

POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
PGADMIN_DEFAULT_EMAIL = os.getenv("PGADMIN_DEFAULT_EMAIL")
PGADMIN_DEFAULT_PASSWORD = os.getenv("PGADMIN_DEFAULT_PASSWORD")
PGADMIN_DISABLE_POSTFIX = os.getenv("PGADMIN_DISABLE_POSTFIX")
SECRET_KEY = os.getenv("SECRET_KEY")
DOCKER_HOST_DBT_DIR = os.getenv("DOCKER_HOST_DBT_DIR")
DOCKER_HOST_PROJECT_DBT_DIR = os.getenv("DOCKER_HOST_PROJECT_DBT_DIR")
